### ISSUE TITLE
can't access the lab environment

### ISSUE THREAD

**Issue by vanshita12345** [RedHatQuickCourses/instructlab-insurance-lab#1]
Hi, i am doing "InstructLab: Training Merlinite for Parasol Insurance" course. Whenever i launch the course, its directed me to other page where i got the option of lab environment. when i try to open "Parasol Insurance Lab" i did not find Parasol Insurance Lab option to start working with. 
![Screenshot 2024-09-13 182926](https://github.com/user-attachments/assets/2b796421-2f76-4388-b915-097f9da441c8)

**Comment by gregchown** [comment]
I experienced the same issue, when accessing the demo platform via the Partner signin (partner.demo.redhat.com).

**Comment by pvrbharg** [comment]
Same here on Oct 15, 2024 - can not access it using partner id and the portal says I have completed the course - actually I read the content but did not get to do the steps.

**Comment by pvrbharg** [comment]
Hello Red Hat Support,

As a partner - I am supposed to be able to access the Parasol Insurance Lab from the catalog and I want to understand why this has been filtered out.

Also I want to understand - when would I get access to this lab? Please help.. Thanks.

[Parasol Insurance Lab](https://demo.redhat.com/catalog?item=babylon-catalog-dev/rhdp.instructlab-parasol-rhel.dev&utm_source=webapp&utm_medium=share-link)

**Comment by kknoxrht** [comment]
Hey all,

Updated the Lab Environment page with replacement link which will direct to a new version Parasol Insurance lab which is now the  **Parasol Insurance AI Workshop**.  This should resolve the issue of trying of determine which lab to use.    Thank you for letting us know.
